### ISSUE TITLE
A cpp solution to the following problem

### ISSUE THREAD

**Issue by TalionSlade** [TalionSlade/LeetStuff#3]
Given the root of a binary tree, determine if it is a valid binary search tree (BST).

A valid BST is defined as follows:

The left subtree of a node contains only nodes with keys less than the node's key.
The right subtree of a node contains only nodes with keys greater than the node's key.
Both the left and right subtrees must also be binary search trees.

**Comment by Ishita-0112** [comment]
Would like to work on this issue! Assign me please.
